# compare this with 2piQA/.travis.yml
# hooks on github may need adjustment.
 
# use containers (so no sudo)
sudo: false

language: python

cache: pip
# and Sphinx and FreeCAD 
#  directories:
#     - /usr/lib/freecad/lib
#     - ${HOME}/.FreeCAD/???

# trigger on pushes to master branch
branches:
  only:
   - master

#specify multiple parallel jobs
matrix:
    include:
        - python: 2.7
#          env: FREECAD=freecad
#        - python: 2.7
#          env: FREECAD=freecad-daily
#
#        - python: 3.6
#          env: FREECAD=freecad
#        - python: 3.6
#          env: FREECAD=freecad-daily

#It might be possible to use FreeCAD AppImage but then Sphinx needs to find 
# python libraries inside the AppImage, or sphinx needs to run inside the image.

# this ppa seems to be out-of-date
# https://launchpad.net/~freecad-maintainers/+archive/ubuntu/freecad-daily

#before_install:
  - sudo add-apt-repository --assume-yes ppa:freecad-maintainers/freecad-stable
#  - sudo add-apt-repository --assume-yes ppa:freecad-maintainers/freecad-daily
#  - sudo apt-get update --assume-yes
#  - sudo apt-get install--assume-yes  freecad
  
install:
#  # Install Anaconda
#  - echo PYTHON_VERSION $PYTHON_VERSION
#  - echo TRAVIS_PYTHON_VERSION $TRAVIS_PYTHON_VERSION
#  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
#      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
#    else
#      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#    fi
#  - bash miniconda.sh -b -p $HOME/miniconda
#  - export PATH="$HOME/miniconda/bin:$PATH"
#  - hash -r
#  - conda config --set always_yes yes --set changeps1 no
#  - conda update -q conda
#  - conda config --add channels conda-forge
#  - conda update -q conda
#conda create -n FC_test freecad
#source activate FC_test
#conda init bash # nodifies .bashrc
#conda activate  FC_test
#bash
#conda deactivate # removes modifications to .bashrc

install:
  - pip install -U sphinx
#  - pip3 install -U sphinx
  - which sphinx-build
  - sphinx-build --version

#  - export FREECAD=freecad
#  - echo FREECAD is ${FREECAD}
#  - pip install -U pip ${FREECAD}
#  - which ${FREECAD}
#https://github.com/FreeCAD/FreeCAD.git
#  - wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
#  - chmod +x ./appimageupdatetool-x86_64.AppImage

#  - wget https://github.com/FreeCAD/FreeCAD/releases/download/0.18.1/FreeCAD_0.18-16110-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage
#  - chmod +x ./FreeCAD*.AppImage

#  - ./appimageupdatetool.AppImage path/to/old/FreeCAD.AppImage ./path/to/updated/FreeCAD.AppImage

#  - ${FREECAD} --console --version this still opens a window

script:
  - OS_TAG=`uname -i`_`uname -o`
  - echo OS_TAG is ${OS_TAG} 
  - echo PWD is ${PWD} 
  - cd EgFreeCAD
  - make doctest
  - make html

# need next depending on deploy of html
#  - git clone https://${GITHUB_TOKEN}@github.com/pdgilbert/EgFreeCAD.git  ${FREECAD}/${OS_TAG}
#  - cd ${FREECAD}/${OS_TAG}
#  - git checkout  ${FREECAD}/${OS_TAG}


# deploy html to ??
after_success:
  - echo ${FREECAD}/${OS_TAG} success

#  - git push # origin HEAD:${FREECAD}/${OS_TAG}


