#!/bin/sh

version="0.1"

usage="Usage:\n  ZZ=\`./freecad--version freecad\`\n  ZZ=\`./freecad--version freecad-daily\`\n"

case $# in
    0)echo "${usage}"; exit 1 ;;
    1) ;;
    *) echo "${usage}"; exit 1 ;;
  esac

CMD="import sys;[sys.stdout.write(ln.split(' ')[1].split(',')[0]) for ln in sys.stdin]; sys.stdout.flush()"

case ${1} in
  -h|--help)
    echo "${usage}"; exit 0 ;;
  -v|--version)
    echo "${version}"; exit 0 ;;
  *)   break ;;
esac

${1} --console <<EOF | head -n 1  | python -c "$CMD" 
quit()
EOF
